services:
  - type: web
    name: cyber-calendar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PASS_HJ
        sync: false
      - key: PASS_SK
        sync: false
      - key: PASS_JH
        sync: false
